# Generated by Django 4.1.7 on 2023-11-27 03:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0002_usuario_calificacion_vehiculo_conductor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viaje',
            name='destino',
        ),
        migrations.RemoveField(
            model_name='viaje',
            name='fecha_hora_termino',
        ),
        migrations.AlterField(
            model_name='viaje',
            name='tarifa',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(3000)]),
        ),
    ]
