# Generated by Django 4.1.7 on 2023-11-27 03:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0003_remove_viaje_destino_remove_viaje_fecha_hora_termino_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viaje',
            name='usuario_pasajero',
        ),
        migrations.AddField(
            model_name='viaje',
            name='pasajeros',
            field=models.ManyToManyField(related_name='viajes_pasajero', to=settings.AUTH_USER_MODEL),
        ),
    ]
