# Generated by Django 4.1.7 on 2023-12-02 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0004_remove_viaje_usuario_pasajero_viaje_pasajeros'),
    ]

    operations = [
        migrations.AddField(
            model_name='viaje',
            name='latitud',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='viaje',
            name='longitud',
            field=models.FloatField(null=True),
        ),
    ]
